### PR TITLE
Fix duplicate step registration

### LINKED ISSUE #52: Bindings break when importing steps into other steps
It seems that the binding registration of steps no longer work properly if a step file is imported by other step files.  

From what I can tell, this issue occurs when:
1. Step file A imports step file B
2. Step file A comes alphabetically before step file B

Repo: https://github.com/justinbhopper/tsflow-issue

In this repo, there is a test that purposefully fails.  However, the tests do not fail and it appears the test that was meant to fail never gets run and is completely ignored by cucumber.

My best guess is something is going wrong in the binding registry.  Perhaps the `FormSteps` class is being registered twice?  Or perhaps its registration is being corrupted having been loaded into memory before tsflow expects?

### PR DESCRIPTION
**Pull request by justinbhopper**
This fixes #52.  The root causes were:

1. The steps were being registered multiple times.
2. The "Ambiguous step definitions" error was never being displayed, due to the Error being returned instead of thrown.  This was making it appear as though steps were being ignored.

This PR fixes the "Ambiguous step definitions" error so it is now thrown.

This PR also adds a duplicate check using the Callsite's filename and lineNumber.  If the filename and lineNumber is the same, then we should assume the step file is being compiled again and we should not re-register the binding.

### CODE REVIEW

**Comment by justinbhopper** [comment]
@timjroberts @mikehaas763 

Is there anything I can do to help give insight or better context to this fix?

**Comment by justinbhopper** [comment]
@wudong What are the chances of this PR getting merged?  I ask because it seems like nothing has been committed since Dec 2018, so I'm wondering if the repo has been abandoned.

**Comment by timjroberts** [comment]
I started this as an experiment in applying TypeScript decorators as bindings to CucumberJS and didn't really expect it to be as widely used as it is. I no longer work in the Node.js space so I haven't contributed to it in a long time.

@justinbhopper, @wudong - would either of you like to come on board as contributors and keep the project going?

**Comment by wudong** [comment]
@timjroberts I am happy to be a contributor of the project. My company does use it quite a lot and would like to see it to grow!

**Comment by timjroberts** [comment]
@wudong - An invite has been sent!

**Comment by mikehaas763** [comment]
That's awesome to see more people interested in contributing back! Welcome!

File: cucumber-tsflow/src/binding-decorator.ts [hunk 1]
```diff
@@ -158,7 +158,7 @@ function bindStepDefinition(stepBinding: StepBinding): void {
 
     return (bindingObject[
       matchingStepBindings[0].targetPropertyKey
-    ] as () => void).apply(bindingObject, arguments);
+    ] as () => void).apply(bindingObject, arguments as any);
```
Comment (mikehaas763) [inline cucumber-tsflow/src/binding-decorator.ts:161]: Is there any way to avoid the `any` cast here and on line 224?

**Comment by mikehaas763** [comment]
@justinbhopper thanks for the contribution! I'm assuming you ran the test suite ran successfully, as well as the husky lint and formatting commands? We could really use a pipeline that hooks into the github status checks 🙂

**Comment by wudong** [comment]
Yeah, it is a good idea. I see if i can add github action into the project.

File: cucumber-tsflow/src/binding-decorator.ts (hunk 1 above)
Comment (justinbhopper) [reply cucumber-tsflow/src/binding-decorator.ts:161]: Yes, its possible with further changes.  I was trying to keep changes to a minimal, and this project is already littered with `any` casts.

**Comment by justinbhopper** [comment]
I've removed the changes that were unrelated to the PR, such as the `as any` castings.  VSCode's intellisense was mistakenly using the latest version of TS instead of the workspace's version.

**Comment by wudong** [comment]
@mikehaas763 @timjroberts 
I have merged this PR and bump the path version. But I cannot publish to the npm. can either one of you publish it or grant me permission? my npm login is 'wudongliu'.

**Comment by justinbhopper** [comment]
@mikehaas763 @timjroberts 

Can either of you please respond?  Maintenance on this repo is dead in the water without someone available to grant publish permissions.

**Comment by timjroberts** [comment]
@wudong - I've just added you as a maintainer to https://www.npmjs.com/package/cucumber-tsflow

**Comment by wudong** [comment]
Thanks @timjroberts.  new release go out fine now. 
However, i was meant to add the CI/CD pipeline with github actions, so we could make release more easily.
But I don't seem to have permission to add the npm token into the repo (missing the 'setting' tab), anyone know is contributor supposed to be able to do that ?

**Comment by timjroberts** [comment]
Unfortunately @wudong, I have no experience using GitHub Actions, and this repo pre-dates them. I did find this article which seems to document how you might do it though:

https://sergiodxa.com/articles/github-actions-npm-publish/

It appears to use repository level secrets to store the NPM token.

**Comment by justinbhopper** [comment]
@wudong The new npm version just published does not appear to have a `dist` folder

image
